server:
  port: 9992
spring:  application:    name: inventory-microservice
    
eureka:  instance:    hostname: localhost  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://${eureka.instance.hostname}:1111/eureka